In [16]:
import pandas as pd 
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.compose import ColumnTransformer # metadata
from sklearn.preprocessing import OneHotEncoder # take action on that metadata
from sklearn.preprocessing import StandardScaler # for feature scaling
from sklearn.model_selection import train_test_split  
from  tensorflow  import keras
from tensorflow.keras import Sequential
from tensorflow.keras  import layers


In [2]:
# loading data
url1='https://raw.githubusercontent.com/redashu/Datasets/master/bank.csv'
dataset=pd.read_csv(url1)
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [5]:
# creating features and label in dataset
features=dataset.iloc[:,3:-1].values
label=dataset.iloc[:,-1].values
print(features)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [6]:
# calling label encoder 
le=LabelEncoder() # M(1) & F(0) encoding -- number 
features[:,2]=le.fit_transform(features[:,2])
print(features)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [9]:
# preparing metadata
ct1=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1])], remainder='passthrough')
features=np.array(ct1.fit_transform(features))
print(features)
#                               encoding type , method , column 

[[1.0 0.0 1.0 ... 1 1 101348.88]
 [1.0 0.0 0.0 ... 0 1 112542.58]
 [1.0 0.0 1.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 1.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 1.0 ... 1 0 38190.78]]


In [12]:
# data split 
trainX,testX,trainY,testY=train_test_split(features,label,test_size=0.2)

In [13]:
# feature scaling 
sc=StandardScaler() # normalization and standardization 
scaled_trainX=sc.fit_transform(trainX)
print(scaled_trainX)

[[ 0.58370131 -0.58370131 -0.996257   ... -1.54451509 -1.03511621
  -0.72405262]
 [ 0.58370131 -0.58370131  1.00375706 ...  0.6474524  -1.03511621
   1.53554941]
 [ 0.58370131 -0.58370131 -0.996257   ...  0.6474524  -1.03511621
  -1.6961797 ]
 ...
 [ 0.58370131 -0.58370131 -0.996257   ...  0.6474524   0.96607511
   0.02774491]
 [ 0.58370131 -0.58370131  1.00375706 ...  0.6474524   0.96607511
   1.19867179]
 [ 0.58370131 -0.58370131  1.00375706 ...  0.6474524  -1.03511621
   0.17032159]]


In [15]:
# creatin ANN model --sequential 
myann2=Sequential()

In [ ]:
# adding Intermediate / hidden layers 
myann2.add(layers.Dense(20,activation='relu')) # first hidden layer 
myann2.add()
myann2.add()
myann2.add(1,activation='sigmoid') # output layer 