In [9]:
import pandas as pd 
import numpy as np
from sklearn.preprocessing import LabelEncoder # str to number
from sklearn.compose import ColumnTransformer # metadata
from sklearn.preprocessing import OneHotEncoder # take action on that metadata
from sklearn.preprocessing import StandardScaler # for feature scaling
from sklearn.model_selection import train_test_split  
#from  tensorflow  import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense


In [2]:
# loading data
url1='https://raw.githubusercontent.com/redashu/Datasets/master/bank.csv'
dataset=pd.read_csv(url1)
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [3]:
# creating features and label in dataset
features=dataset.iloc[:,3:-1].values
label=dataset.iloc[:,-1].values
print(features)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [4]:
# calling label encoder 
le=LabelEncoder() # M(1) & F(0) encoding -- number 
features[:,2]=le.fit_transform(features[:,2])
print(features)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [5]:
# preparing metadata
ct1=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1])], remainder='passthrough')
features=np.array(ct1.fit_transform(features))
print(features)
#                               encoding type , method , column 

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [6]:
# data split 
trainX,testX,trainY,testY=train_test_split(features,label,test_size=0.2)

In [7]:
# feature scaling 
sc=StandardScaler() # normalization and standardization 
scaled_trainX=sc.fit_transform(trainX)
print(scaled_trainX)

[[-1.00125078 -0.57908232  1.74017165 ...  0.6474524   0.97432938
   0.92644141]
 [-1.00125078 -0.57908232  1.74017165 ...  0.6474524  -1.02634696
  -0.46677281]
 [-1.00125078 -0.57908232  1.74017165 ... -1.54451509  0.97432938
   0.05879389]
 ...
 [-1.00125078 -0.57908232  1.74017165 ...  0.6474524   0.97432938
   0.40830927]
 [ 0.99875078 -0.57908232 -0.57465595 ...  0.6474524  -1.02634696
   0.57370925]
 [-1.00125078 -0.57908232  1.74017165 ...  0.6474524   0.97432938
  -0.08699838]]


In [11]:
# creatin ANN model --sequential 
myann2=Sequential()

In [12]:
# adding Intermediate / hidden layers 
myann2.add(Dense(20,activation='relu')) # first hidden layer 
myann2.add(Dense(20,activation='relu'))
myann2.add(Dense(20,activation='relu'))
myann2.add(Dense(1,activation='sigmoid')) # output layer 

In [13]:
# compile -- defining final layer cost function for back prapogation
myann2.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
# if optimizer is adam then we user stochstic gradient decent

In [14]:
# time to train data
myann2.fit(scaled_trainX,trainY,epochs=30,batch_size=40)

Epoch 1/30
200/200 [==============================] - 0s 357us/step - loss: 0.4853 - accuracy: 0.7776
Epoch 2/30
200/200 [==============================] - 0s 341us/step - loss: 0.4115 - accuracy: 0.8270
Epoch 3/30
200/200 [==============================] - 0s 339us/step - loss: 0.3718 - accuracy: 0.8476
Epoch 4/30
200/200 [==============================] - 0s 337us/step - loss: 0.3510 - accuracy: 0.8581
Epoch 5/30
200/200 [==============================] - 0s 337us/step - loss: 0.3431 - accuracy: 0.8583
Epoch 6/30
200/200 [==============================] - 0s 365us/step - loss: 0.3378 - accuracy: 0.8615
Epoch 7/30
200/200 [==============================] - 0s 326us/step - loss: 0.3360 - accuracy: 0.8608
Epoch 8/30
200/200 [==============================] - 0s 338us/step - loss: 0.3326 - accuracy: 0.8619
Epoch 9/30
200/200 [==============================] - 0s 394us/step - loss: 0.3305 - accuracy: 0.8643
Epoch 10/30
200/200 [==============================] - 0s 349us/step - loss: 0.327

In [16]:
# prediction 
myann2.predict(sc.transform([[812,0,0,1,1,32,7,230000,3,0,1,120000]]))

1/1 [==============================] - 0s 17ms/step


array([0.], dtype=float32)